spring:
    message: Production Environment
    
logging:
    level:
        root:ERROR
    pattern:
        console: %d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n